---
name: CI

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        platform: ['iOS Simulator,name=iPhone 8']
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  bazel:
    name: bazel
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: bazel
        run: make bazel
